/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BibliaRouteImport } from './routes/biblia'
import { Route as ComeceRouteImport } from './routes/comece'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as GratidaoRouteImport } from './routes/gratidao'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as ApiPublicCaktoWebhookRouteImport } from './routes/api/public/cakto-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliaRoute = BibliaRouteImport.update({
  id: '/biblia',
  path: '/biblia',
  getParentRoute: () => rootRouteImport,
} as any)
const ComeceRoute = ComeceRouteImport.update({
  id: '/comece',
  path: '/comece',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const GratidaoRoute = GratidaoRouteImport.update({
  id: '/gratidao',
  path: '/gratidao',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaktoWebhookRoute = ApiPublicCaktoWebhookRouteImport.update({
  id: '/api/public/cakto-webhook',
  path: '/api/public/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/comece': typeof ComeceRoute
  '/conta': typeof ContaRoute
  '/gratidao': typeof GratidaoRoute
  '/instalar': typeof InstalarRoute
  '/plano': typeof PlanoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/comece': typeof ComeceRoute
  '/conta': typeof ContaRoute
  '/gratidao': typeof GratidaoRoute
  '/instalar': typeof InstalarRoute
  '/plano': typeof PlanoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblia': typeof BibliaRoute
  '/comece': typeof ComeceRoute
  '/conta': typeof ContaRoute
  '/gratidao': typeof GratidaoRoute
  '/instalar': typeof InstalarRoute
  '/plano': typeof PlanoRoute
  '/api/public/cakto-webhook': typeof ApiPublicCaktoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblia'
    | '/comece'
    | '/conta'
    | '/gratidao'
    | '/instalar'
    | '/plano'
    | '/api/public/cakto-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblia'
    | '/comece'
    | '/conta'
    | '/gratidao'
    | '/instalar'
    | '/plano'
    | '/api/public/cakto-webhook'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/biblia'
    | '/comece'
    | '/conta'
    | '/gratidao'
    | '/instalar'
    | '/plano'
    | '/api/public/cakto-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BibliaRoute: typeof BibliaRoute
  ComeceRoute: typeof ComeceRoute
  ContaRoute: typeof ContaRoute
  GratidaoRoute: typeof GratidaoRoute
  InstalarRoute: typeof InstalarRoute
  PlanoRoute: typeof PlanoRoute
  ApiPublicCaktoWebhookRoute: typeof ApiPublicCaktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblia': {
      id: '/biblia'
      path: '/biblia'
      fullPath: '/biblia'
      preLoaderRoute: typeof BibliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comece': {
      id: '/comece'
      path: '/comece'
      fullPath: '/comece'
      preLoaderRoute: typeof ComeceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gratidao': {
      id: '/gratidao'
      path: '/gratidao'
      fullPath: '/gratidao'
      preLoaderRoute: typeof GratidaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cakto-webhook': {
      id: '/api/public/cakto-webhook'
      path: '/api/public/cakto-webhook'
      fullPath: '/api/public/cakto-webhook'
      preLoaderRoute: typeof ApiPublicCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BibliaRoute: BibliaRoute,
  ComeceRoute: ComeceRoute,
  ContaRoute: ContaRoute,
  GratidaoRoute: GratidaoRoute,
  InstalarRoute: InstalarRoute,
  PlanoRoute: PlanoRoute,
  ApiPublicCaktoWebhookRoute: ApiPublicCaktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
